### ISSUE TITLE
dgl版本问题

### ISSUE THREAD

**Issue by kbk12** [CRIPAC-DIG/DGSR#1]
老师您好，我搜的最新版本的dgl是0.6.1，没有找到dgl 0.7.2版本，请问您是在哪下载的

**Comment by ZM7** [comment]
> 老师您好，我搜的最新版本的dgl是0.6.1，没有找到dgl 0.7.2版本，请问您是在哪下载的

可以参考DGL官网的安装教程

**Comment by kbk12** [comment]
老师您好，查找了相关资料针对DGL版本只看到0.6.1，在跑模型的时候报一些参数错误，你在跑模型的时候安装的是0.7.2版本吗

**Comment by ZM7** [comment]
> 老师您好，查找了相关资料针对DGL版本只看到0.6.1，在跑模型的时候报一些参数错误，你在跑模型的时候安装的是0.7.2版本吗
是的，我用的是0.7.2的版本，因为涉及到图的采样，低版本可能不支持。官网是可以找到各个版本的。
![image](https://user-images.githubusercontent.com/26395667/162693145-8ecd8818-30f4-45db-9b34-823034e08c98.png)
