### ISSUE TITLE
是否存在数据泄露问题？

### ISSUE THREAD

**Issue by ShelveyJ** [CRIPAC-DIG/DGSR#11]
作者你好，在阅读代码过程中，发现在为某一个用户构建动态图的过程可能会把别的用户的target item也会包含进去，这是否会导致数据泄露？

**Comment by ZM7** [comment]
> 

您能告诉我大概是代码哪一部分吗，我看下再反馈给您

**Comment by ShelveyJ** [comment]
![image](https://user-images.githubusercontent.com/52660191/218032168-fbe1c8ae-6b78-4729-9016-acdf05e39af2.png)
以上代码中，生成图的过程中并没有去掉测试集，在generate_user函数中，针对每个用户生成动态图的过程中，可能会把其他用户的测试集包含进去，比如为用户1生成动态图的过程中，在时间戳范围内，可能会把其他用户的target_item包含进用户1的动态图中。

**Comment by ShelveyJ** [comment]
不知我理解的对不对，请您看看

**Comment by ZM7** [comment]
> 不知我理解的对不对，请您看看

我个人理解的应该不会。测试集中的item应该大部分都在训练集出现过，所以可能其他用户的target_item天然的在训练集里面。有可能对一些训练集中从没出现过的实体有一定提升作用，但是应该也非常有限
