### ISSUE TITLE
Bug regarding Train, Validation, Test split

### ISSUE THREAD

**Issue by Linkerbrain** [CRIPAC-DIG/DGSR#3]
Hello,

Thank you for the very interesting paper, really cool concept.

I had a question about how the Train/Validation/Test split happens in the code:

https://github.com/ZM7/DGSR/blob/2293cbdf6e043e9afc02d313e15458124dbd31b7/new_data.py#L112-L123

It seems to me that using this logic:

- items of `time == 0` ... `time == split_point - 2` are added to the train data
- items of `time == split_point - 3` is added to the validation data
- items of `time != split_point - 3` is added to the test data

This would mean that the items in the training data are also added to the test data.

In the following table this is illustrated further:
| time | train | validation | test |
|------|-------|------------|------|
| 0    | x     |            | x    |
| 1    | x     |            | x    |
| 2    | x     |            | x    |
| 3    | x     | x          |      |
| 4    | x     |            | x    |
| 5    |       |            | x    |
| 6    |       |            | x    |

This seems very odd. I was wondering if this was intended or a bug?

**Comment by ZM7** [comment]
> Hello,
> 
> Thank you for the very interesting paper, really cool concept.
> 
> I had a question about how the Train/Validation/Test split happens in the code:
> 
> https://github.com/ZM7/DGSR/blob/2293cbdf6e043e9afc02d313e15458124dbd31b7/new_data.py#L112-L123
> 
> It seems to me that using this logic:
> 
> * items of `time == 0` ... `time == split_point - 2` are added to the train data
> * items of `time == split_point - 3` is added to the validation data
> * items of `time != split_point - 3` is added to the test data
> 
> This would mean that the items in the training data are also added to the test data.
> 
> In the following table this is illustrated further:
> 
> time	train	validation	test
> 0	x		x
> 1	x		x
> 2	x		x
> 3	x	x	
> 4	x		x
> 5			x
> 6			x
> This seems very odd. I was wondering if this was intended or a bug?


Thank you for your interest in our work.  Sorry, we made a bug in the refine code process. We checked the previous results and no test data was used in the training process.  We have fixed our bug in ```new_data.py```.
