### ISSUE TITLE
No such file or directory: './Data/sample.csv'

### ISSUE THREAD

**Issue by homaonchij** [CRIPAC-DIG/DGSR#5]
您好，我想请问一下运行 new_data.py 时会出现 ‘No such file or directory: './Data/sample.csv'的问题要怎么解决呢？

**Comment by ZM7** [comment]
sample.csv是为了调代码自己切得一个小数据集，可以从我提供的数据集里面简单切分出一个，或者直接跑我们提供的数据集。
