### ISSUE TITLE
Question about Weight matrix definition in paper

### ISSUE THREAD

**Issue by Linkerbrain** [CRIPAC-DIG/DGSR#6]
Hello,

Thanks again for the interesting research. We were further investigating the paper and I had a question.

Is the weight matrix 'W1' in equation 5 the same as the weight matrix 'W1' in equation 7? And is this also the same as in equation 14?

I was under the the impression this was true, however in equation 5 and 7 the weights are multiplied with the item embedding and in equation 14 it is multiplied with user embedding.

![image](https://user-images.githubusercontent.com/30159673/166253273-7621695a-cd1b-4268-8b59-6af707b0ee98.png)

Thank you for your research and kind regards,
Linkerbrain

**Comment by ZM7** [comment]
Sorry, there may be a typo. The  weight matrix 'W1' in equation 5 is  same as the weight matrix 'W1' in equation 7.  The matrix W_1 and W_2 shoud be exchanged in Eq(13) and (14). I will fix it in arxiv version.
